import { Head, Link, useForm } from '@inertiajs/react';
import AdminLayout from '@/Layouts/AdminLayout';
function Status({ value }) { return <span className="inline-flex rounded bg-neutral-100 px-2 py-1 text-[10px] font-bold uppercase tracking-wider text-neutral-700">{value || '-'}</span>; }
export default function Activities({ participant, placement, activities = [], logbooks = [], attendances = [] }) {
 const activePlacement = placement || participant?.placement; const activityRows = activities.data || activities || []; const { data, setData, post, processing, errors, reset } = useForm({ activity_date: '', title: '', description: '', hours: '' });
 const submit = e => { e.preventDefault(); post(`/mahasiswa/mbkm/placements/${activePlacement.id}/activities`, { onSuccess: () => reset() }); };
 if (!activePlacement) return <AdminLayout title="Aktivitas MBKM"><Head title="Aktivitas MBKM" /><div className="p-6 text-sm text-neutral-500">Anda belum memiliki penempatan MBKM aktif.</div></AdminLayout>;
 return <AdminLayout title="Aktivitas MBKM"><Head title="Aktivitas MBKM" /><div className="min-h-dvh space-y-6 bg-neutral-50 p-6"><div className="bg-gradient-to-r from-brand-900 via-brand-800 to-brand-700 p-6 text-white"><Link href="/mahasiswa/mbkm/programs" className="text-sm underline">← Program MBKM</Link><p className="mt-4 text-xs uppercase tracking-widest">Aktivitas MBKM</p><h1 className="text-2xl font-bold">{activePlacement.title}</h1><p className="mt-1 text-sm text-white/80">{activePlacement.partner?.name || activePlacement.mbkm_partner?.name || ''}</p></div><div className="grid grid-cols-1 gap-6 lg:grid-cols-3"><section className="border bg-white p-6 lg:col-span-2"><h2 className="mb-4 text-sm font-bold uppercase">Riwayat Aktivitas</h2><div className="divide-y">{activityRows.map(activity => <article key={activity.id} className="py-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="font-bold">{activity.title}</p><p className="mt-1 text-xs text-neutral-500">{activity.activity_date} · {activity.hours} jam</p></div><Status value={activity.status} /></div>{activity.description && <p className="mt-2 text-sm text-neutral-600">{activity.description}</p>}</article>)}{activityRows.length === 0 && <p className="py-6 text-center text-sm text-neutral-500">Belum ada aktivitas yang dicatat.</p>}</div></section><section className="border bg-white p-6"><h2 className="mb-4 text-sm font-bold uppercase">Catat Aktivitas</h2><form onSubmit={submit} className="space-y-3"><div><label className="mb-1 block text-xs font-bold uppercase">Tanggal</label><input required type="date" value={data.activity_date} onChange={e => setData('activity_date', e.target.value)} className="w-full border-neutral-300 text-sm" /><p className="text-xs text-red-600">{errors.activity_date}</p></div><div><label className="mb-1 block text-xs font-bold uppercase">Judul</label><input required value={data.title} onChange={e => setData('title', e.target.value)} className="w-full border-neutral-300 text-sm" /><p className="text-xs text-red-600">{errors.title}</p></div><div><label className="mb-1 block text-xs font-bold uppercase">Durasi (jam)</label><input required min="0" step="0.5" type="number" value={data.hours} onChange={e => setData('hours', e.target.value)} className="w-full border-neutral-300 text-sm" /></div><div><label className="mb-1 block text-xs font-bold uppercase">Deskripsi</label><textarea value={data.description} onChange={e => setData('description', e.target.value)} rows="4" className="w-full border-neutral-300 text-sm" /></div><button disabled={processing} className="w-full bg-black px-4 py-3 text-xs font-bold text-white">{processing ? 'Menyimpan...' : 'Simpan Aktivitas'}</button></form></section></div></div></AdminLayout>;
}
