import { Head, Link, router, useForm } from '@inertiajs/react';
import AdminLayout from '@/Layouts/AdminLayout';
function Badge({ value }) { return <span className="inline-flex rounded bg-neutral-100 px-2 py-1 text-[10px] font-bold uppercase tracking-wider text-neutral-700">{value || '-'}</span>; }
export default function Show({ program, application, eligibility = [], eligibilityProblems = [] }) {
 const { data, setData, post, processing, errors } = useForm({ motivation: application?.motivation || '', notes: application?.notes || '' });
 const problems = eligibilityProblems.length ? eligibilityProblems : eligibility;
 const createDraft = e => { e.preventDefault(); post(`/mahasiswa/mbkm/programs/${program.id}/applications`); };
 const submit = () => confirm('Ajukan pendaftaran MBKM ini? Data tidak dapat diubah setelah diajukan.') && router.post(`/mahasiswa/mbkm/applications/${application.id}/submit`);
 return <AdminLayout title="Detail MBKM"><Head title={`MBKM - ${program.name}`} /><div className="min-h-dvh space-y-6 bg-neutral-50 p-6"><div className="bg-gradient-to-r from-brand-900 via-brand-800 to-brand-700 p-6 text-white"><Link href="/mahasiswa/mbkm/programs" className="text-sm underline">← Semua Program</Link><p className="mt-4 text-xs uppercase tracking-widest">{program.code}</p><h1 className="text-2xl font-bold">{program.name}</h1><p className="mt-2 text-sm text-white/80">{program.program_type?.name || program.mbkm_program_type?.name} · {program.partner?.name || program.mbkm_partner?.name || 'Mitra akan diinformasikan'}</p></div><div className="grid grid-cols-1 gap-6 lg:grid-cols-3"><section className="space-y-5 border bg-white p-6 lg:col-span-2"><div><h2 className="text-sm font-bold uppercase">Informasi Pendaftaran</h2><p className="mt-2 text-sm text-neutral-600">Pendaftaran dibuka {program.registration_start} sampai {program.registration_end}.</p></div><div><h2 className="text-sm font-bold uppercase">Persyaratan</h2><p className="mt-2 whitespace-pre-line text-sm text-neutral-600">{Array.isArray(program.requirements) ? program.requirements.join('\n') : program.requirements || 'Tidak ada persyaratan tambahan.'}</p></div>{problems.length > 0 && <div className="border border-red-200 bg-red-50 p-4 text-sm text-red-800"><p className="font-bold">Pendaftaran belum memenuhi syarat</p><ul className="mt-2 list-disc pl-5">{problems.map((problem, index) => <li key={index}>{problem}</li>)}</ul></div>}</section><aside className="border bg-white p-6"><h2 className="text-sm font-bold uppercase">Pendaftaran Saya</h2>{application ? <div className="mt-4 space-y-4"><p className="text-sm">Nomor: <b>{application.application_number}</b></p><Badge value={application.status} />{application.status === 'draft' && <><textarea value={data.motivation} onChange={e => setData('motivation', e.target.value)} className="w-full border-neutral-300 text-sm" rows="5" placeholder="Motivasi mengikuti program" /><p className="text-xs text-red-600">{errors.motivation}</p><button disabled={processing || problems.length > 0} onClick={submit} className="w-full bg-black px-4 py-3 text-xs font-bold text-white disabled:opacity-50">Ajukan Pendaftaran</button></>}<Link href={`/mahasiswa/mbkm/applications/${application.id}`} className="block text-center text-xs font-bold underline">Lihat status pendaftaran</Link></div> : <form onSubmit={createDraft} className="mt-4 space-y-3"><p className="text-sm text-neutral-600">Buat draft pendaftaran untuk melanjutkan pengajuan.</p><button disabled={processing || problems.length > 0} className="w-full bg-black px-4 py-3 text-xs font-bold text-white disabled:opacity-50">Buat Draft Pendaftaran</button></form>}</aside></div></div></AdminLayout>;
}
