import { Head, router } from '@inertiajs/react';
import { useState } from 'react';
import AdminLayout from '@/Layouts/AdminLayout';
import { collectionRows, courseName, DomainBadge, EmptyRow, ObeHeader, Panel } from '@/Components/ObeUi';

const valueOf = (item) => item.capaian ?? item.achievement ?? item.percentage ?? item.nilai;

export default function Index({ kelasKuliah = [], courseClasses = [], selectedClass = null, cpmks = [], achievements = [], cplAchievements = [], filters = {} }) {
    const classes = collectionRows(kelasKuliah).length ? collectionRows(kelasKuliah) : collectionRows(courseClasses); const initialClassId = filters.kelas_kuliah_id || filters.course_class_id || selectedClass?.id || ''; const [selectedId, setSelectedId] = useState(initialClassId);
    const cpmkRows = collectionRows(cpmks); const achievementRows = collectionRows(achievements).length ? collectionRows(achievements) : collectionRows(cplAchievements);
    return <AdminLayout title="OBE Kelas Saya"><Head title="OBE Kelas Saya" /><div className="min-h-dvh space-y-6 bg-neutral-50 p-6"><ObeHeader eyebrow="Dosen · Outcome-Based Education" title="CAPAIAN PEMBELAJARAN KELAS" description="Tinjau CPMK dan capaian kelas yang Anda ampu. Data ini bersifat baca saja." />
        {classes.length > 0 && <Panel><form onSubmit={(e) => { e.preventDefault(); router.get('/dosen/obe', { kelas_kuliah_id: selectedId }, { preserveState: true, replace: true }); }} className="flex flex-wrap gap-3"><select value={selectedId} onChange={(e) => setSelectedId(e.target.value)} className="min-w-64 flex-1 border-neutral-300 text-sm"><option value="">Pilih kelas yang diampu</option>{classes.map((item) => <option key={item.id} value={item.id}>{item.kode_kelas || item.nama_kelas || item.class_name || 'Kelas'} — {courseName(item.mata_kuliah || item.course || item)}</option>)}</select><button className="bg-black px-4 py-2 text-xs font-bold text-white">Tampilkan</button></form></Panel>}
        {selectedClass && <Panel><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-widest text-neutral-500">Kelas terpilih</p><h2 className="mt-1 text-xl font-bold">{courseName(selectedClass.mata_kuliah || selectedClass.course || selectedClass)}</h2><p className="mt-1 text-sm text-neutral-500">{selectedClass.kode_kelas || selectedClass.nama_kelas || selectedClass.class_name || 'Kelas'} · {selectedClass.semester?.nama_semester || selectedClass.period?.nama || ''}</p></div><span className="border border-neutral-300 px-3 py-2 text-xs font-bold text-neutral-700">Baca saja</span></div></Panel>}
        <div className="grid gap-6 xl:grid-cols-[1.35fr_1fr]"><Panel className="!p-0"><div className="border-b border-neutral-200 px-5 py-4"><h2 className="font-bold">CPMK dan Sub-CPMK</h2></div><div className="divide-y divide-neutral-100">{cpmkRows.map((cpmk) => <article key={cpmk.id} className="p-5"><div className="flex flex-wrap items-center gap-2"><span className="font-bold">{cpmk.kode || cpmk.code}</span>{(cpmk.domain || cpmk.category) && <DomainBadge value={cpmk.domain || cpmk.category} />}</div><p className="mt-2 text-sm font-semibold text-neutral-900">{cpmk.nama || cpmk.title || cpmk.name}</p><p className="mt-1 text-sm text-neutral-500">{cpmk.deskripsi || cpmk.description || '-'}</p><ul className="mt-3 space-y-1 border-l-2 border-indigo-100 pl-3 text-xs text-neutral-600">{collectionRows(cpmk.sub_cpmks || cpmk.subCpmks).map((sub) => <li key={sub.id}><b>{sub.kode || sub.code}</b> — {sub.nama || sub.title || sub.name}</li>)}</ul></article>)}{cpmkRows.length === 0 && <p className="p-8 text-center text-sm text-neutral-500">Belum ada CPMK pada kelas ini.</p>}</div></Panel>
            <Panel className="!p-0"><div className="border-b border-neutral-200 px-5 py-4"><h2 className="font-bold">Ringkasan Capaian</h2></div><table className="min-w-full text-sm"><thead className="bg-neutral-50 text-left text-xs uppercase text-neutral-500"><tr><th className="px-4 py-3">Capaian</th><th className="px-4 py-3">Nilai</th></tr></thead><tbody className="divide-y divide-neutral-100">{achievementRows.map((item) => { const value = valueOf(item); return <tr key={item.id || item.cpl_id || item.cpmk_id}><td className="px-4 py-3"><p className="font-bold">{item.cpl?.kode || item.cpmk?.kode || item.kode || item.code}</p><p className="text-xs text-neutral-500">{item.cpl?.nama || item.cpmk?.nama || item.nama || item.title || ''}</p></td><td className="px-4 py-3"><span className={`inline-flex px-2 py-1 text-xs font-bold ${Number(value || 0) >= 70 ? 'bg-emerald-100 text-emerald-800' : 'bg-amber-100 text-amber-800'}`}>{value === null || value === undefined ? 'Belum ada' : `${Number(value).toFixed(1)}%`}</span></td></tr>; })}{achievementRows.length === 0 && <EmptyRow colSpan={2}>Capaian belum tersedia untuk kelas ini.</EmptyRow>}</tbody></table></Panel></div></div></AdminLayout>;
}
