import { Head, router, useForm } from '@inertiajs/react';
import { useEffect, useState } from 'react';
import AdminLayout from '@/Layouts/AdminLayout';
import { collectionRows, courseName, EmptyRow, Field, ObeHeader, Panel, StatusBadge } from '@/Components/ObeUi';

const emptyCpmk = { mata_kuliah_id: '', kurikulum_id: '', code: '', title: '', description: '', sequence: 1, status: 'aktif' };
const emptySub = { code: '', title: '', description: '', sequence: 1, status: 'aktif' };

export default function Index({ cpmks = [], mataKuliahs = [], courses = [], kurikulums = [], curriculums = [], filters = {} }) {
    const rows = collectionRows(cpmks); const courseRows = collectionRows(mataKuliahs).length ? collectionRows(mataKuliahs) : collectionRows(courses); const curricula = collectionRows(kurikulums).length ? collectionRows(kurikulums) : collectionRows(curriculums);
    const [courseId, setCourseId] = useState(filters.mata_kuliah_id || filters.course_id || ''); const [openId, setOpenId] = useState(null);
    const cpmkForm = useForm(emptyCpmk); const subForm = useForm(emptySub);
    useEffect(() => { if (courseId) cpmkForm.setData('mata_kuliah_id', courseId); }, [courseId]);
    const filter = (event) => { event.preventDefault(); router.get('/admin/obe/cpmk', { kurikulum_id: cpmkForm.data.kurikulum_id }, { preserveState: true, replace: true }); };
    const addCpmk = (event) => { event.preventDefault(); cpmkForm.post('/admin/obe/cpmk', { onSuccess: () => cpmkForm.reset() }); };
    const addSub = (event, cpmk) => { event.preventDefault(); subForm.post(`/admin/obe/cpmk/${cpmk.id}/sub-cpmk`, { onSuccess: () => subForm.reset() }); };
    const removeSub = (cpmk, sub) => { if (confirm(`Hapus ${sub.kode || sub.code}?`)) router.delete(`/admin/obe/cpmk/${cpmk.id}/sub-cpmk/${sub.id}`); };
    return <AdminLayout title="CPMK & Sub-CPMK"><Head title="CPMK & Sub-CPMK" /><div className="min-h-dvh space-y-6 bg-neutral-50 p-6"><ObeHeader title="CPMK & SUB-CPMK" description="Tetapkan capaian setiap mata kuliah, lalu rincikan indikator Sub-CPMK." />
        <Panel><form onSubmit={filter} className="flex flex-wrap gap-3"><select value={courseId} onChange={(e) => setCourseId(e.target.value)} className="min-w-64 flex-1 border-neutral-300 text-sm"><option value="">Pilih mata kuliah untuk dikelola</option>{courseRows.map((course) => <option key={course.id} value={course.id}>{course.kode_mata_kuliah || course.kode || course.code} — {courseName(course)}</option>)}</select><button className="bg-black px-4 py-2 text-xs font-bold text-white">Tampilkan</button></form></Panel>
        {courseId && <Panel><h2 className="mb-4 text-lg font-bold text-neutral-900">Tambah CPMK</h2><form onSubmit={addCpmk} className="grid gap-4 md:grid-cols-2"><Field label="Kurikulum" error={cpmkForm.errors.kurikulum_id}><select value={cpmkForm.data.kurikulum_id} onChange={(e) => cpmkForm.setData('kurikulum_id', e.target.value)} className="w-full border-neutral-300 text-sm"><option value="">Pilih kurikulum</option>{curricula.map((item) => <option key={item.id} value={item.id}>{item.nama || item.name || item.kode}</option>)}</select></Field><Field label="Kode CPMK" error={cpmkForm.errors.code}><input required value={cpmkForm.data.code} onChange={(e) => cpmkForm.setData('code', e.target.value)} className="w-full border-neutral-300 text-sm" placeholder="CPMK-01" /></Field><Field label="Capaian Mata Kuliah" error={cpmkForm.errors.title} className="md:col-span-2"><input required value={cpmkForm.data.title} onChange={(e) => cpmkForm.setData('title', e.target.value)} className="w-full border-neutral-300 text-sm" /></Field><Field label="Deskripsi" error={cpmkForm.errors.description} className="md:col-span-2"><textarea rows="3" value={cpmkForm.data.description} onChange={(e) => cpmkForm.setData('description', e.target.value)} className="w-full border-neutral-300 text-sm" /></Field><div className="md:col-span-2"><button disabled={cpmkForm.processing} className="bg-black px-4 py-2 text-sm font-bold text-white disabled:opacity-50">{cpmkForm.processing ? 'Menyimpan...' : 'Tambah CPMK'}</button></div></form></Panel>}
        <Panel className="!p-0"><div className="border-b border-neutral-200 px-5 py-4"><h2 className="font-bold">Daftar CPMK</h2></div><div className="divide-y divide-neutral-200">{rows.map((cpmk) => { const subs = collectionRows(cpmk.sub_cpmks || cpmk.subCpmks); const opened = openId === cpmk.id; return <div key={cpmk.id} className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><span className="font-bold">{cpmk.kode || cpmk.code}</span><StatusBadge value={cpmk.status} /></div><p className="mt-1 font-semibold text-neutral-900">{cpmk.nama || cpmk.title || cpmk.name}</p><p className="mt-1 text-sm text-neutral-500">{cpmk.deskripsi || cpmk.description || 'Tidak ada deskripsi.'}</p></div><button onClick={() => { setOpenId(opened ? null : cpmk.id); subForm.reset(); }} className="border border-neutral-300 px-3 py-2 text-xs font-bold hover:bg-neutral-50">{opened ? 'Tutup Sub-CPMK' : `Kelola Sub-CPMK (${subs.length})`}</button></div>{opened && <div className="mt-5 border-t border-neutral-200 pt-5"><div className="space-y-2">{subs.map((sub) => <div key={sub.id} className="flex items-start justify-between gap-4 border border-neutral-200 bg-neutral-50 p-3"><div><p className="text-sm font-bold">{sub.kode || sub.code} — {sub.nama || sub.title || sub.name}</p>{(sub.deskripsi || sub.description) && <p className="mt-1 text-xs text-neutral-500">{sub.deskripsi || sub.description}</p>}</div><button onClick={() => removeSub(cpmk, sub)} className="text-xs font-bold text-red-700 underline">Hapus</button></div>)}{subs.length === 0 && <p className="py-2 text-sm text-neutral-500">Belum ada Sub-CPMK.</p>}</div><form onSubmit={(event) => addSub(event, cpmk)} className="mt-4 grid gap-3 border-t border-neutral-200 pt-4 md:grid-cols-[10rem_1fr_auto]"><input required value={subForm.data.code} onChange={(e) => subForm.setData('code', e.target.value)} className="border-neutral-300 text-sm" placeholder="Sub-01.1" /><input required value={subForm.data.title} onChange={(e) => subForm.setData('title', e.target.value)} className="border-neutral-300 text-sm" placeholder="Indikator Sub-CPMK" /><button disabled={subForm.processing} className="bg-black px-4 py-2 text-xs font-bold text-white">Tambah</button></form>{subForm.errors.title && <p className="mt-1 text-xs text-red-600">{subForm.errors.title}</p>}</div>}</div>; })}{rows.length === 0 && <div className="p-8 text-center text-sm text-neutral-500">Pilih mata kuliah untuk melihat dan mengelola CPMK.</div>}</div></Panel></div></AdminLayout>;
}
