import { Head, Link, useForm } from '@inertiajs/react';
import AdminLayout from '@/Layouts/AdminLayout';

const labels = { submitted: 'Menunggu review', reviewed: 'Selesai ditinjau', revision: 'Perlu revisi', cancelled: 'Dibatalkan' };
function Badge({ status }) { const tone = status === 'completed' ? 'bg-emerald-100 text-emerald-800' : status === 'revision' ? 'bg-amber-100 text-amber-800' : 'bg-blue-100 text-blue-800'; return <span className={`inline-flex rounded px-2 py-1 text-[10px] font-bold uppercase tracking-wider ${tone}`}>{labels[status] || status || '-'}</span>; }

export default function Sessions({ thesis = null, sessions = [] }) {
    const supervisors = thesis?.active_supervisors || thesis?.supervisors?.filter((item) => item.status === 'active') || [];
    const { data, setData, post, processing, errors, reset } = useForm({ thesis_supervisor_id: '', meeting_date: '', topic: '', student_notes: '' });
    const rows = sessions.length ? sessions : (thesis?.sessions || []);
    const submit = (event) => { event.preventDefault(); post(`/mahasiswa/tugas-akhir/${thesis.id}/sessions`, { preserveScroll: true, onSuccess: () => reset() }); };
    return <AdminLayout title="Bimbingan Tugas Akhir"><Head title="Bimbingan Tugas Akhir" /><div className="min-h-dvh space-y-6 bg-neutral-50 p-6">
        <header className="flex flex-wrap items-start justify-between gap-4 bg-gradient-to-r from-slate-800 to-indigo-700 p-6 text-white"><div><p className="text-xs font-bold uppercase tracking-widest">Tugas Akhir</p><h1 className="mt-1 text-2xl font-bold">SESI BIMBINGAN</h1><p className="mt-1 text-sm text-white/80">Ajukan bimbingan dan tindak lanjuti masukan pembimbing.</p></div><Link href="/mahasiswa/tugas-akhir" className="text-sm font-semibold underline">Kembali ke tugas akhir</Link></header>
        {!thesis ? <section className="border border-dashed bg-white p-8 text-center text-sm text-neutral-500">Ajukan judul tugas akhir terlebih dahulu untuk membuat permintaan bimbingan.</section> : <>
            <div className="grid grid-cols-1 gap-6 xl:grid-cols-3"><section className="border bg-white p-6 xl:col-span-2"><h2 className="text-sm font-bold uppercase">Riwayat bimbingan</h2><div className="mt-4 space-y-4">{rows.map((session) => <article key={session.id} className="border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-bold">{session.topic || 'Bimbingan tugas akhir'}</p><p className="mt-1 text-xs text-neutral-500">{session.meeting_date ? new Date(session.meeting_date).toLocaleDateString('id-ID', { dateStyle: 'long' }) : 'Tanggal menunggu konfirmasi'} · {session.supervisor?.dosen?.nama_lengkap || 'Pembimbing'}</p></div><Badge status={session.status} /></div>{session.student_notes && <p className="mt-3 text-sm text-neutral-600"><b>Catatan Anda:</b> {session.student_notes}</p>}{session.feedback && <div className="mt-3 border-l-4 border-indigo-500 bg-indigo-50 p-3 text-sm text-indigo-950"><b>Masukan pembimbing:</b><p className="mt-1">{session.feedback}</p></div>}</article>)}{rows.length === 0 && <p className="py-8 text-center text-sm text-neutral-500">Belum ada sesi bimbingan tercatat.</p>}</div></section>
                <aside className="h-fit border bg-white p-6"><h2 className="text-sm font-bold uppercase">Ajukan bimbingan</h2>{supervisors.length > 0 ? <form onSubmit={submit} className="mt-4 space-y-4"><label className="block text-sm font-medium">Pembimbing<select value={data.thesis_supervisor_id} onChange={(event) => setData('thesis_supervisor_id', event.target.value)} className="mt-1 block w-full border-neutral-300 text-sm" required><option value="">Pilih pembimbing</option>{supervisors.map((supervisor) => <option key={supervisor.id} value={supervisor.id}>{supervisor.dosen?.nama_lengkap || '-'}</option>)}</select></label><label className="block text-sm font-medium">Tanggal usulan<input type="date" value={data.meeting_date} onChange={(event) => setData('meeting_date', event.target.value)} className="mt-1 block w-full border-neutral-300 text-sm" required /></label><label className="block text-sm font-medium">Topik bimbingan<input value={data.topic} onChange={(event) => setData('topic', event.target.value)} className="mt-1 block w-full border-neutral-300 text-sm" required placeholder="Contoh: Revisi Bab 3" />{errors.topic && <p className="mt-1 text-xs text-red-600">{errors.topic}</p>}</label><label className="block text-sm font-medium">Catatan / perkembangan<textarea value={data.student_notes} onChange={(event) => setData('student_notes', event.target.value)} className="mt-1 block w-full border-neutral-300 text-sm" rows="5" required placeholder="Jelaskan perkembangan dan hal yang ingin didiskusikan." /></label><button disabled={processing} className="w-full bg-black px-4 py-3 text-sm font-bold text-white disabled:opacity-50">{processing ? 'Mengirim...' : 'Kirim Permintaan'}</button></form> : <p className="mt-4 text-sm text-neutral-500">Permintaan bimbingan dapat diajukan setelah pembimbing ditetapkan.</p>}</aside></div>
        </>}</div></AdminLayout>;
}
