import { Head, Link, useForm } from '@inertiajs/react';
import { useState } from 'react';
import AdminLayout from '@/Layouts/AdminLayout';

const labels = { submitted: 'Menunggu review', under_review: 'Dalam review', title_revision: 'Revisi judul', title_approved: 'Judul disetujui', supervisor_assignment: 'Penetapan pembimbing', proposal: 'Proposal', proposal_rejected: 'Proposal ditolak', proposal_approved: 'Proposal disetujui', seminar_proposal: 'Seminar proposal', research: 'Penelitian', result_seminar: 'Seminar hasil', thesis_defense: 'Sidang akhir', revision: 'Revisi', revision_verified: 'Revisi terverifikasi', completed: 'Selesai' };
function Badge({ status }) { const tone = status === 'completed' ? 'bg-emerald-100 text-emerald-800' : status === 'proposal_rejected' ? 'bg-rose-100 text-rose-800' : status?.includes('revision') ? 'bg-amber-100 text-amber-800' : 'bg-blue-100 text-blue-800'; return <span className={`inline-flex rounded px-2 py-1 text-[10px] font-bold uppercase tracking-wider ${tone}`}>{labels[status] || status || '-'}</span>; }

export default function Show({ thesis = null, lecturers = [], supervisorCandidates = [] }) {
    const candidates = supervisorCandidates.length ? supervisorCandidates : lecturers;
    const allSubmissions = thesis?.title_submissions || [];
    // Hanya pengajuan yang belum ditinjau yang boleh diputuskan.
    const titleSubmissions = allSubmissions.filter((item) => item.status === 'submitted');
    const [submissionId, setSubmissionId] = useState(titleSubmissions[0]?.id || '');
    const { data: review, setData: setReview, post: postReview, processing: reviewing, errors: reviewErrors } = useForm({ decision: 'approved', selected_title: titleSubmissions[0]?.title || thesis?.title || '', comment: '' });
    const { data: assignment, setData: setAssignment, post: postAssignment, processing: assigning, errors: assignmentErrors } = useForm({ dosen_id: '', role: 'pembimbing_1' });
    const { data: finalization, setData: setFinalization, post: postFinalization, processing: finalizing, errors: finalizationErrors } = useForm({ grade: thesis?.final_grade || '', grade_point: thesis?.final_grade_point || '' });

    if (!thesis) return <AdminLayout title="Detail Tugas Akhir"><Head title="Detail Tugas Akhir" /><div className="border bg-white p-8 text-center text-sm text-neutral-500">Data tugas akhir tidak ditemukan.</div></AdminLayout>;

    const selectedSubmission = titleSubmissions.find((item) => String(item.id) === String(submissionId));
    // Judul yang sah hanya boleh berasal dari usulan mahasiswa ( ThesisService::reviewTitle ).
    const candidateTitles = [selectedSubmission?.title, ...(selectedSubmission?.alternate_titles || [])].filter(Boolean);
    const activeSupervisors = (thesis.supervisors || []).filter((item) => item.status === 'active');
    const canFinalize = thesis.status === 'revision_verified' && (thesis.documents || []).some((item) => item.type === 'final');

    const chooseSubmission = (id) => {
        const submission = titleSubmissions.find((item) => String(item.id) === String(id));
        setSubmissionId(id);
        setReview('selected_title', submission?.title || '');
    };
    const reviewTitle = (event) => { event.preventDefault(); if (submissionId) postReview(`/admin/tugas-akhir/title-submissions/${submissionId}/review`, { preserveScroll: true }); };
    const assign = (event) => { event.preventDefault(); postAssignment(`/admin/tugas-akhir/${thesis.id}/supervisors`, { preserveScroll: true }); };
    const finalize = (event) => { event.preventDefault(); postFinalization(`/admin/tugas-akhir/${thesis.id}/finalize`, { preserveScroll: true }); };

    return (
        <AdminLayout title="Detail Tugas Akhir">
            <Head title={`Tugas Akhir - ${thesis.mahasiswa?.nama_lengkap || thesis.student?.nama_lengkap || ''}`} />
            <div className="min-h-dvh space-y-6 bg-neutral-50 p-6">
                <header className="bg-gradient-to-r from-slate-800 to-indigo-700 p-6 text-white"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest">Detail tugas akhir</p><h1 className="mt-1 text-2xl font-bold">{thesis.mahasiswa?.nama_lengkap || thesis.student?.nama_lengkap || 'Mahasiswa'}</h1><p className="mt-1 text-sm text-white/80">{thesis.mahasiswa?.nim || thesis.student?.nim || '-'} · {thesis.program_study?.nama_prodi || thesis.prodi?.nama_prodi || '-'}</p></div><div className="flex items-center gap-3"><Badge status={thesis.status} /><Link href="/admin/tugas-akhir" className="text-sm font-semibold underline">Kembali</Link></div></div></header>

                <section className="border bg-white p-6"><p className="text-xs font-bold uppercase tracking-widest text-neutral-500">Judul aktif</p><h2 className="mt-2 text-xl font-bold">{thesis.title || '-'}</h2><div className="mt-4 grid gap-4 text-sm md:grid-cols-3"><div><p className="text-xs uppercase text-neutral-500">Jenis</p><p className="mt-1 font-semibold">{thesis.type?.name || (typeof thesis.type === 'string' ? thesis.type : 'Skripsi')}</p></div><div><p className="text-xs uppercase text-neutral-500">Semester</p><p className="mt-1 font-semibold">{thesis.semester?.nama_semester || '-'}</p></div><div><p className="text-xs uppercase text-neutral-500">Bimbingan</p><p className="mt-1 font-semibold">{thesis.sessions?.length ?? 0} sesi</p></div></div></section>

                <div className="grid grid-cols-1 gap-6 xl:grid-cols-2">
                    <section className="border bg-white p-6"><h2 className="text-sm font-bold uppercase">Review judul</h2>{titleSubmissions.length ? <form onSubmit={reviewTitle} className="mt-5 space-y-4"><label className="block text-sm font-medium">Pengajuan judul<select value={submissionId} onChange={(event) => chooseSubmission(event.target.value)} className="mt-1 block w-full border-neutral-300 text-sm">{titleSubmissions.map((submission) => <option key={submission.id} value={submission.id}>Versi {submission.version}: {submission.title}</option>)}</select></label><label className="block text-sm font-medium">Judul yang dipilih<select value={review.selected_title} onChange={(event) => setReview('selected_title', event.target.value)} className="mt-1 block w-full border-neutral-300 text-sm" required>{candidateTitles.map((title) => <option key={title} value={title}>{title}</option>)}</select>{reviewErrors.selected_title && <p className="mt-1 text-xs text-red-600">{reviewErrors.selected_title}</p>}</label><label className="block text-sm font-medium">Keputusan<select value={review.decision} onChange={(event) => setReview('decision', event.target.value)} className="mt-1 block w-full border-neutral-300 text-sm"><option value="approved">Setujui judul</option><option value="revision">Minta revisi</option><option value="rejected">Tolak pengajuan</option></select></label><label className="block text-sm font-medium">Catatan review<textarea value={review.comment} onChange={(event) => setReview('comment', event.target.value)} className="mt-1 block w-full border-neutral-300 text-sm" rows="4" placeholder="Sampaikan catatan yang jelas untuk mahasiswa." /></label><button disabled={reviewing} className="bg-black px-5 py-3 text-sm font-bold text-white disabled:opacity-50">Simpan keputusan judul</button></form> : <p className="mt-4 text-sm text-neutral-500">Tidak ada pengajuan judul yang menunggu review.</p>}</section>

                    <section className="border bg-white p-6"><h2 className="text-sm font-bold uppercase">Penetapan pembimbing</h2><form onSubmit={assign} className="mt-5 space-y-4"><label className="block text-sm font-medium">Peran<select value={assignment.role} onChange={(event) => setAssignment('role', event.target.value)} className="mt-1 block w-full border-neutral-300 text-sm"><option value="pembimbing_1">Pembimbing 1</option><option value="pembimbing_2">Pembimbing 2</option></select></label><label className="block text-sm font-medium">Dosen<select value={assignment.dosen_id} onChange={(event) => setAssignment('dosen_id', event.target.value)} className="mt-1 block w-full border-neutral-300 text-sm" required><option value="">Pilih dosen</option>{candidates.map((lecturer) => <option key={lecturer.id} value={lecturer.id}>{lecturer.nama_lengkap || lecturer.name}</option>)}</select>{assignmentErrors.dosen_id && <p className="mt-1 text-xs text-red-600">{assignmentErrors.dosen_id}</p>}</label><button disabled={assigning} className="bg-black px-5 py-3 text-sm font-bold text-white disabled:opacity-50">Tetapkan pembimbing</button></form><div className="mt-6 border-t pt-5"><p className="text-xs font-bold uppercase text-neutral-500">Pembimbing aktif</p><div className="mt-3 space-y-2">{activeSupervisors.map((item) => <div className="flex justify-between border p-3 text-sm" key={item.id}><span>{item.role === 'pembimbing_1' ? 'Pembimbing 1' : 'Pembimbing 2'}</span><b>{item.dosen?.nama_lengkap || '-'}</b></div>)}{activeSupervisors.length === 0 && <p className="text-sm text-neutral-500">Belum ada pembimbing aktif.</p>}</div></div></section>
                </div>

                <section className="border border-emerald-200 bg-emerald-50 p-6"><h2 className="text-sm font-bold uppercase text-emerald-900">Finalisasi tugas akhir</h2><p className="mt-1 text-sm text-emerald-800">Pastikan nilai, dokumen akhir, dan seluruh revisi telah diverifikasi sebelum finalisasi.</p>{canFinalize || thesis.status === 'completed' ? <form onSubmit={finalize} className="mt-4 grid max-w-2xl gap-4 sm:grid-cols-3"><label className="block text-sm font-medium text-emerald-950">Nilai akhir<input value={finalization.grade} onChange={(event) => setFinalization('grade', event.target.value)} className="mt-1 block w-full border-emerald-200 text-sm" required placeholder="A" /></label><label className="block text-sm font-medium text-emerald-950">Bobot nilai<input type="number" min="0" max="4" step="0.01" value={finalization.grade_point} onChange={(event) => setFinalization('grade_point', event.target.value)} className="mt-1 block w-full border-emerald-200 text-sm" required placeholder="4.00" />{finalizationErrors.grade_point && <p className="mt-1 text-xs text-red-600">{finalizationErrors.grade_point}</p>}</label><div className="flex items-end"><button disabled={finalizing || thesis.status === 'completed'} className="w-full bg-emerald-700 px-5 py-3 text-sm font-bold text-white disabled:opacity-50">{thesis.status === 'completed' ? 'Sudah difinalisasi' : 'Finalisasi'}</button></div></form> : <p className="mt-4 border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">Finalisasi baru tersedia setelah status <b>revisi terverifikasi</b> dan dokumen akhir (final) diunggah mahasiswa.</p>}</section>
            </div>
        </AdminLayout>
    );
}
