import { Head, useForm } from '@inertiajs/react';
import AdminLayout from '@/Layouts/AdminLayout';
import { BackLink, collectionRows, curriculumName, Field, ObeHeader, Panel } from '@/Components/ObeUi';

export default function Create({ kurikulums = [], curriculums = [] }) {
    const curricula = collectionRows(kurikulums).length ? collectionRows(kurikulums) : collectionRows(curriculums);
    const { data, setData, post, processing, errors } = useForm({ prodi_id: '', kurikulum_id: '', code: '', name: '', description: '', domain: '', sequence: 1, status: 'aktif' });
    const setCurriculum = (id) => {
        const curriculum = curricula.find((item) => String(item.id) === id);
        setData({ ...data, kurikulum_id: id, prodi_id: curriculum?.prodi_id || '' });
    };

    return <AdminLayout title="Tambah CPL"><Head title="Tambah CPL" /><div className="min-h-dvh space-y-6 bg-neutral-50 p-6"><ObeHeader title="TAMBAH CPL" action={<BackLink />} /><form onSubmit={(e) => { e.preventDefault(); post('/admin/obe/cpl'); }}><Panel className="space-y-5"><div className="grid gap-4 md:grid-cols-2"><Field label="Kurikulum" error={errors.kurikulum_id}><select required value={data.kurikulum_id} onChange={(e) => setCurriculum(e.target.value)} className="w-full border-neutral-300 text-sm"><option value="">Pilih kurikulum</option>{curricula.map((item) => <option key={item.id} value={item.id}>{curriculumName(item)}</option>)}</select></Field><Field label="Kode CPL" error={errors.code}><input required value={data.code} onChange={(e) => setData('code', e.target.value)} className="w-full border-neutral-300 text-sm" placeholder="CPL-01" /></Field><Field label="Judul CPL" error={errors.name} className="md:col-span-2"><input required value={data.name} onChange={(e) => setData('name', e.target.value)} className="w-full border-neutral-300 text-sm" placeholder="Kemampuan yang diharapkan dari lulusan" /></Field><Field label="Domain" error={errors.domain}><select value={data.domain} onChange={(e) => setData('domain', e.target.value)} className="w-full border-neutral-300 text-sm"><option value="">Pilih domain</option><option value="sikap">Sikap</option><option value="pengetahuan">Pengetahuan</option><option value="keterampilan_umum">Keterampilan Umum</option><option value="keterampilan_khusus">Keterampilan Khusus</option></select></Field><Field label="Urutan" error={errors.sequence}><input type="number" min="0" value={data.sequence} onChange={(e) => setData('sequence', e.target.value)} className="w-full border-neutral-300 text-sm" /></Field><Field label="Deskripsi" error={errors.description} className="md:col-span-2"><textarea rows="5" value={data.description} onChange={(e) => setData('description', e.target.value)} className="w-full border-neutral-300 text-sm" /></Field></div><button disabled={processing} className="bg-black px-5 py-3 text-sm font-bold text-white disabled:opacity-50">{processing ? 'Menyimpan...' : 'Simpan CPL'}</button></Panel></form></div></AdminLayout>;
}
