import { Head, useForm } from '@inertiajs/react';
import AdminLayout from '@/Layouts/AdminLayout';
import { BackLink, collectionRows, curriculumName, Field, ObeHeader, Panel } from '@/Components/ObeUi';

export default function Edit({ cpl, kurikulums = [], curriculums = [] }) {
    const curricula = collectionRows(kurikulums).length ? collectionRows(kurikulums) : collectionRows(curriculums);
    const { data, setData, put, processing, errors } = useForm({ code: cpl.code || cpl.kode || '', name: cpl.name || cpl.nama || cpl.title || '', description: cpl.description || cpl.deskripsi || '', domain: cpl.domain || cpl.category || '', sequence: cpl.sequence || cpl.urutan || 1, status: cpl.status || 'aktif' });
    const curriculum = cpl.kurikulum || cpl.curriculum || curricula.find((item) => String(item.id) === String(cpl.kurikulum_id || cpl.curriculum_id));
    return <AdminLayout title="Edit CPL"><Head title="Edit CPL" /><div className="min-h-dvh space-y-6 bg-neutral-50 p-6"><ObeHeader title="EDIT CPL" description={`${data.code} — perbarui tanpa mengubah riwayat kurikulum.`} action={<BackLink />} /><form onSubmit={(e) => { e.preventDefault(); put(`/admin/obe/cpl/${cpl.id}`); }}><Panel className="space-y-5"><div className="grid gap-4 md:grid-cols-2"><Field label="Kurikulum"><p className="border border-neutral-200 bg-neutral-50 px-3 py-2 text-sm text-neutral-600">{curriculumName(curriculum)}</p></Field><Field label="Kode CPL" error={errors.code}><input required value={data.code} onChange={(e) => setData('code', e.target.value)} className="w-full border-neutral-300 text-sm" /></Field><Field label="Judul CPL" error={errors.name} className="md:col-span-2"><input required value={data.name} onChange={(e) => setData('name', e.target.value)} className="w-full border-neutral-300 text-sm" /></Field><Field label="Domain" error={errors.domain}><select value={data.domain} onChange={(e) => setData('domain', e.target.value)} className="w-full border-neutral-300 text-sm"><option value="">Pilih domain</option><option value="sikap">Sikap</option><option value="pengetahuan">Pengetahuan</option><option value="keterampilan_umum">Keterampilan Umum</option><option value="keterampilan_khusus">Keterampilan Khusus</option></select></Field><Field label="Status" error={errors.status}><select value={data.status} onChange={(e) => setData('status', e.target.value)} className="w-full border-neutral-300 text-sm"><option value="aktif">Aktif</option><option value="nonaktif">Nonaktif</option></select></Field><Field label="Deskripsi" error={errors.description} className="md:col-span-2"><textarea rows="5" value={data.description} onChange={(e) => setData('description', e.target.value)} className="w-full border-neutral-300 text-sm" /></Field></div><button disabled={processing} className="bg-black px-5 py-3 text-sm font-bold text-white disabled:opacity-50">{processing ? 'Menyimpan...' : 'Simpan Perubahan'}</button></Panel></form></div></AdminLayout>;
}
