import { Head, Link, router } from '@inertiajs/react';
import { useState } from 'react';
import AdminLayout from '@/Layouts/AdminLayout';
import { collectionRows, curriculumName, DomainBadge, EmptyRow, ObeHeader, Panel, StatusBadge } from '@/Components/ObeUi';

export default function Index({ cpls = [], kurikulums = [], curriculums = [], prodis = [], programStudies = [], filters = {} }) {
    const [search, setSearch] = useState(filters.search || '');
    const [kurikulumId, setKurikulumId] = useState(filters.kurikulum_id || filters.curriculum_id || '');
    const rows = collectionRows(cpls); const curricula = collectionRows(kurikulums).length ? collectionRows(kurikulums) : collectionRows(curriculums);
    const studies = collectionRows(prodis).length ? collectionRows(prodis) : collectionRows(programStudies);
    const submit = (event) => { event.preventDefault(); router.get('/admin/obe/cpl', { search, kurikulum_id: kurikulumId }, { preserveState: true, replace: true }); };
    return <AdminLayout title="CPL"><Head title="CPL" /><div className="min-h-dvh space-y-6 bg-neutral-50 p-6"><ObeHeader title="CAPAIAN PEMBELAJARAN LULUSAN" description="Kelola CPL sesuai versi kurikulum dan program studi." action={<Link href="/admin/obe/cpl/create" className="bg-white px-4 py-2 text-sm font-bold text-black">+ Tambah CPL</Link>} />
        <form onSubmit={submit} className="flex flex-wrap gap-3 border border-neutral-200 bg-white p-4"><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Cari kode, judul, atau deskripsi..." className="min-w-56 flex-1 border-neutral-300 text-sm" /><select value={kurikulumId} onChange={(e) => setKurikulumId(e.target.value)} className="border-neutral-300 text-sm"><option value="">Semua kurikulum</option>{curricula.map((item) => <option key={item.id} value={item.id}>{curriculumName(item)}</option>)}</select><button className="bg-black px-4 py-2 text-xs font-bold text-white">Cari</button></form>
        {studies.length > 0 && <p className="text-xs text-neutral-500">CPL ditampilkan berdasarkan kurikulum pada program studi yang dipilih.</p>}
        <Panel className="overflow-x-auto !p-0"><table className="min-w-full text-sm"><thead className="bg-neutral-50 text-left text-xs uppercase text-neutral-500"><tr><th className="px-4 py-3">Kode</th><th className="px-4 py-3">Capaian Pembelajaran</th><th className="px-4 py-3">Kurikulum</th><th className="px-4 py-3">Domain</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Aksi</th></tr></thead><tbody className="divide-y divide-neutral-100">{rows.map((cpl) => <tr key={cpl.id}><td className="px-4 py-3 font-bold">{cpl.kode || cpl.code}</td><td className="px-4 py-3"><p className="font-semibold text-neutral-900">{cpl.nama || cpl.title || cpl.name}</p><p className="mt-1 max-w-xl text-xs text-neutral-500">{cpl.deskripsi || cpl.description || '-'}</p></td><td className="px-4 py-3 text-xs">{curriculumName(cpl.kurikulum || cpl.curriculum)}</td><td className="px-4 py-3"><DomainBadge value={cpl.domain || cpl.category} /></td><td className="px-4 py-3"><StatusBadge value={cpl.status} /></td><td className="px-4 py-3"><Link href={`/admin/obe/cpl/${cpl.id}/edit`} className="text-xs font-bold underline">Edit</Link></td></tr>)}{rows.length === 0 && <EmptyRow colSpan={6}>Belum ada CPL untuk filter ini.</EmptyRow>}</tbody></table></Panel></div></AdminLayout>;
}
