import type { ReferenceDefinition, ReferenceKey } from '@/types/reference';

/**
 * Registry referensi PDDikti.
 *
 * Nama `act` diambil dari daftar Web Service Neo Feeder yang terverifikasi
 * (211 act pada dokumentasi Postman PDDikti Feeder / dictionary Neo Feeder).
 * Bila `act` kosong, referensi tersebut statis di SIAKAD dan tidak ada act
 * khusus pada Web Service.
 */
export const referenceDefinitions: Record<ReferenceKey, ReferenceDefinition> = {
    'perguruan-tinggi': {
        key: 'perguruan-tinggi',
        label: 'Perguruan Tinggi',
        group: 'institusi',
        act: 'GetProfilPT',
        idField: 'id_perguruan_tinggi',
        labelField: 'nama_perguruan_tinggi',
        description: 'Profil perguruan tinggi yang terdaftar pada PDDikti.',
        requiredForSync: true,
    },
    fakultas: {
        key: 'fakultas',
        label: 'Fakultas',
        group: 'institusi',
        act: 'GetFakultas',
        idField: 'id_fakultas',
        labelField: 'nama_fakultas',
        description: 'Daftar fakultas pada PDDikti.',
    },
    'program-studi': {
        key: 'program-studi',
        label: 'Program Studi',
        group: 'institusi',
        act: 'GetProdi',
        idField: 'id_prodi',
        labelField: 'nama_program_studi',
        description: 'Program studi pada PDDikti beserta kode dan jenjang. Wajib dipetakan sebelum sinkronisasi akademik.',
        requiredForSync: true,
    },
    semester: {
        key: 'semester',
        label: 'Semester',
        group: 'akademik',
        act: 'GetSemester',
        idField: 'id_semester',
        labelField: 'nama_semester',
        description: 'Kode semester PDDikti (format tahun + periode, mis. 20251).',
        requiredForSync: true,
    },
    'tahun-ajaran': {
        key: 'tahun-ajaran',
        label: 'Tahun Ajaran',
        group: 'akademik',
        act: 'GetTahunAjaran',
        idField: 'id_tahun_ajaran',
        labelField: 'nama_tahun_ajaran',
        description: 'Tahun ajaran PDDikti.',
    },
    periode: {
        key: 'periode',
        label: 'Periode Pelaporan',
        group: 'akademik',
        act: 'GetPeriode',
        idField: 'id_periode',
        labelField: 'nama_periode',
        description: 'Periode pelaporan yang dibuka PDDikti untuk perguruan tinggi.',
        requiredForSync: true,
        notes: 'Beberapa versi Neo Feeder membatasi sinkronisasi hanya pada periode yang sedang dibuka.',
    },
    'jenjang-pendidikan': {
        key: 'jenjang-pendidikan',
        label: 'Jenjang Pendidikan',
        group: 'akademik',
        act: 'GetJenjangPendidikan',
        idField: 'id_jenjang_pendidikan',
        labelField: 'nama_jenjang_pendidikan',
        description: 'Referensi jenjang (D3, D4, S1, S2, S3).',
    },
    'bentuk-pendidikan': {
        key: 'bentuk-pendidikan',
        label: 'Bentuk Pendidikan',
        group: 'akademik',
        act: 'GetBentukPendidikan',
        idField: 'id_bentuk_pendidikan',
        labelField: 'nama_bentuk_pendidikan',
        description: 'Bentuk pendidikan (akademik, vokasi, profesi).',
    },
    'skala-nilai': {
        key: 'skala-nilai',
        label: 'Skala Nilai',
        group: 'akademik',
        act: 'GetListSkalaNilaiProdi',
        idField: 'id_skala_nilai',
        labelField: 'nama_skala_nilai',
        description: 'Skala nilai per program studi. Wajib tersedia sebelum mengirim nilai perkuliahan.',
        requiredForSync: true,
        requiresProdi: true,
    },

    agama: {
        key: 'agama',
        label: 'Agama',
        group: 'mahasiswa',
        act: 'GetAgama',
        idField: 'id_agama',
        labelField: 'nama_agama',
        description: 'Referensi agama PDDikti.',
        requiredForSync: true,
    },
    'jenis-kelamin': {
        key: 'jenis-kelamin',
        label: 'Jenis Kelamin',
        group: 'mahasiswa',
        act: '',
        idField: 'id',
        labelField: 'nama',
        description: 'Referensi statis SIAKAD (L/P) — tidak ada act khusus pada Web Service Neo Feeder.',
        notes: 'PDDikti memakai kode huruf L/P pada field jenis_kelamin sehingga tidak perlu pemetaan terpisah.',
    },
    'status-mahasiswa': {
        key: 'status-mahasiswa',
        label: 'Status Mahasiswa',
        group: 'mahasiswa',
        act: 'GetStatusMahasiswa',
        idField: 'id_status_mahasiswa',
        labelField: 'nama_status_mahasiswa',
        description: 'Referensi status mahasiswa (Aktif, Cuti, Lulus, DO, dll).',
        requiredForSync: true,
    },
    'jenis-pendaftaran': {
        key: 'jenis-pendaftaran',
        label: 'Jenis Pendaftaran',
        group: 'mahasiswa',
        act: 'GetJenisPendaftaran',
        idField: 'id_jenis_daftar',
        labelField: 'nama_jenis_daftar',
        description: 'Referensi jenis pendaftaran (baru, transfer, alih jenjang, RPL).',
        requiredForSync: true,
        notes: 'Sejak Neo Feeder 3.x penambahan referensi jenis pendaftaran mempengaruhi alur input mahasiswa baru.',
    },
    'jalur-masuk': {
        key: 'jalur-masuk',
        label: 'Jalur Masuk',
        group: 'mahasiswa',
        act: 'GetJalurMasuk',
        idField: 'id_jalur_masuk',
        labelField: 'nama_jalur_masuk',
        description: 'Referensi jalur masuk mahasiswa.',
        requiredForSync: true,
    },
    'jenis-keluar': {
        key: 'jenis-keluar',
        label: 'Jenis Keluar',
        group: 'mahasiswa',
        act: 'GetJenisKeluar',
        idField: 'id_jenis_keluar',
        labelField: 'nama_jenis_keluar',
        description: 'Referensi jenis keluar (lulus, DO, pindah, mengundurkan diri).',
        requiredForSync: true,
    },
    'jenis-tinggal': {
        key: 'jenis-tinggal',
        label: 'Jenis Tinggal',
        group: 'mahasiswa',
        act: 'GetJenisTinggal',
        idField: 'id_jenis_tinggal',
        labelField: 'nama_jenis_tinggal',
        description: 'Referensi jenis tinggal pada biodata mahasiswa.',
    },
    pembiayaan: {
        key: 'pembiayaan',
        label: 'Jenis Pembiayaan',
        group: 'mahasiswa',
        act: 'GetPembiayaan',
        idField: 'id_pembiayaan',
        labelField: 'nama_pembiayaan',
        description: 'Referensi pembiayaan studi (mandiri, KIP Kuliah, beasiswa).',
        requiredForSync: true,
    },
    'kebutuhan-khusus': {
        key: 'kebutuhan-khusus',
        label: 'Kebutuhan Khusus',
        group: 'mahasiswa',
        act: 'GetKebutuhanKhusus',
        idField: 'id_kebutuhan_khusus',
        labelField: 'nama_kebutuhan_khusus',
        description: 'Referensi kebutuhan khusus mahasiswa.',
    },
    'alat-transportasi': {
        key: 'alat-transportasi',
        label: 'Alat Transportasi',
        group: 'mahasiswa',
        act: 'GetAlatTransportasi',
        idField: 'id_alat_transportasi',
        labelField: 'nama_alat_transportasi',
        description: 'Referensi alat transportasi pada biodata mahasiswa.',
    },
    pekerjaan: {
        key: 'pekerjaan',
        label: 'Pekerjaan',
        group: 'mahasiswa',
        act: 'GetPekerjaan',
        idField: 'id_pekerjaan',
        labelField: 'nama_pekerjaan',
        description: 'Referensi pekerjaan (orang tua/wali).',
    },
    penghasilan: {
        key: 'penghasilan',
        label: 'Penghasilan',
        group: 'mahasiswa',
        act: 'GetPenghasilan',
        idField: 'id_penghasilan',
        labelField: 'nama_penghasilan',
        description: 'Referensi rentang penghasilan orang tua.',
    },

    'status-kepegawaian': {
        key: 'status-kepegawaian',
        label: 'Status Kepegawaian',
        group: 'dosen',
        act: 'GetStatusKepegawaian',
        idField: 'id_status_pegawai',
        labelField: 'nama_status_pegawai',
        description: 'Referensi status kepegawaian dosen.',
        requiredForSync: true,
    },
    'ikatan-kerja': {
        key: 'ikatan-kerja',
        label: 'Ikatan Kerja',
        group: 'dosen',
        act: 'GetIkatanKerjaSdm',
        idField: 'id_ikatan_kerja',
        labelField: 'nama_ikatan_kerja',
        description: 'Referensi ikatan kerja SDM.',
    },
    'jabatan-fungsional': {
        key: 'jabatan-fungsional',
        label: 'Jabatan Fungsional',
        group: 'dosen',
        act: 'GetJabfung',
        idField: 'id_jabfung',
        labelField: 'nama_jabfung',
        description: 'Referensi jabatan fungsional dosen.',
    },
    'pangkat-golongan': {
        key: 'pangkat-golongan',
        label: 'Pangkat / Golongan',
        group: 'dosen',
        act: 'GetPangkatGolongan',
        idField: 'id_pangkat_golongan',
        labelField: 'nama_pangkat_golongan',
        description: 'Referensi pangkat dan golongan dosen.',
    },
    'jenis-sertifikasi': {
        key: 'jenis-sertifikasi',
        label: 'Jenis Sertifikasi',
        group: 'dosen',
        act: 'GetJenisSertifikasi',
        idField: 'id_jenis_sertifikasi',
        labelField: 'nama_jenis_sertifikasi',
        description: 'Referensi jenis sertifikasi dosen.',
    },

    'kategori-kegiatan': {
        key: 'kategori-kegiatan',
        label: 'Kategori Kegiatan',
        group: 'kegiatan',
        act: 'GetKategoriKegiatan',
        idField: 'id_kategori_kegiatan',
        labelField: 'nama_kategori_kegiatan',
        description: 'Referensi kategori kegiatan mahasiswa (MBKM, magang, penelitian, dll).',
        requiredForSync: true,
    },
    'jenis-aktivitas-mahasiswa': {
        key: 'jenis-aktivitas-mahasiswa',
        label: 'Jenis Aktivitas Mahasiswa',
        group: 'kegiatan',
        act: 'GetJenisAktivitasMahasiswa',
        idField: 'id_jenis_aktivitas',
        labelField: 'nama_jenis_aktivitas',
        description: 'Referensi jenis aktivitas mahasiswa untuk pelaporan MBKM.',
        requiredForSync: true,
    },

    wilayah: {
        key: 'wilayah',
        label: 'Wilayah',
        group: 'wilayah',
        act: 'GetWilayah',
        idField: 'id_wilayah',
        labelField: 'nama_wilayah',
        description: 'Referensi wilayah administratif (kecamatan/kelurahan) untuk biodata.',
    },
    negara: {
        key: 'negara',
        label: 'Negara',
        group: 'wilayah',
        act: 'GetNegara',
        idField: 'id_negara',
        labelField: 'nama_negara',
        description: 'Referensi negara untuk kewarganegaraan.',
    },
    'level-wilayah': {
        key: 'level-wilayah',
        label: 'Level Wilayah',
        group: 'wilayah',
        act: 'GetLevelWilayah',
        idField: 'id_level_wilayah',
        labelField: 'nama_level_wilayah',
        description: 'Level wilayah (provinsi, kabupaten, kecamatan).',
    },
};

export const referenceList = Object.values(referenceDefinitions);

export const referenceGroupLabels: Record<ReferenceDefinition['group'], string> = {
    institusi: 'Institusi',
    akademik: 'Akademik',
    mahasiswa: 'Mahasiswa',
    dosen: 'Dosen / SDM',
    kegiatan: 'Kegiatan Mahasiswa',
    wilayah: 'Wilayah & Negara',
};

export const getReferenceDefinition = (key: ReferenceKey): ReferenceDefinition => referenceDefinitions[key];
