<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(): void {
  Schema::create('mbkm_program_types', function (Blueprint $t) { $t->id(); $t->string('code')->unique(); $t->string('name'); $t->text('description')->nullable(); $t->boolean('is_active')->default(true); $t->timestamps(); });
  Schema::create('mbkm_partners', function (Blueprint $t) { $t->id(); $t->string('name'); $t->string('partner_type'); $t->string('email')->nullable(); $t->string('phone')->nullable(); $t->text('address')->nullable(); $t->string('city')->nullable(); $t->string('country')->nullable(); $t->string('status')->default('active'); $t->text('notes')->nullable(); $t->timestamps(); });
  Schema::create('mbkm_programs', function(Blueprint $t) { $t->id(); $t->string('code')->unique(); $t->string('name'); $t->foreignId('mbkm_program_type_id')->constrained()->restrictOnDelete(); $t->foreignId('semester_id')->nullable()->constrained()->nullOnDelete(); $t->foreignId('mbkm_partner_id')->nullable()->constrained()->nullOnDelete(); $t->foreignId('prodi_id')->nullable()->constrained()->nullOnDelete(); $t->date('registration_start'); $t->date('registration_end'); $t->date('implementation_start')->nullable(); $t->date('implementation_end')->nullable(); $t->unsignedInteger('quota')->nullable(); $t->decimal('credit_limit',5,2)->nullable(); $t->string('status')->default('draft'); $t->json('requirements')->nullable(); $t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete(); $t->timestamps(); });
  Schema::create('mbkm_program_targets', function(Blueprint $t) { $t->id(); $t->foreignId('mbkm_program_id')->constrained()->cascadeOnDelete(); $t->foreignId('prodi_id')->nullable()->constrained()->nullOnDelete(); $t->unsignedTinyInteger('minimum_semester')->nullable(); $t->unsignedTinyInteger('maximum_semester')->nullable(); $t->decimal('minimum_gpa',3,2)->nullable(); $t->decimal('minimum_credits',5,2)->nullable(); $t->string('student_status')->nullable(); $t->timestamps(); });
  Schema::create('mbkm_applications', function(Blueprint $t) { $t->id(); $t->foreignId('mbkm_program_id')->constrained()->cascadeOnDelete(); $t->foreignId('mahasiswa_id')->constrained()->restrictOnDelete(); $t->string('application_number')->unique(); $t->string('status')->default('draft'); $t->text('motivation')->nullable(); $t->text('notes')->nullable(); $t->timestamp('submitted_at')->nullable(); $t->timestamps(); $t->unique(['mbkm_program_id','mahasiswa_id']); });
  Schema::create('mbkm_audits', function(Blueprint $t) { $t->id(); $t->nullableMorphs('auditable'); $t->foreignId('user_id')->nullable()->constrained()->nullOnDelete(); $t->string('action'); $t->json('before')->nullable(); $t->json('after')->nullable(); $t->text('reason')->nullable(); $t->timestamps(); });
 }
 public function down(): void { Schema::dropIfExists('mbkm_audits'); Schema::dropIfExists('mbkm_applications'); Schema::dropIfExists('mbkm_program_targets'); Schema::dropIfExists('mbkm_programs'); Schema::dropIfExists('mbkm_partners'); Schema::dropIfExists('mbkm_program_types'); }
};
