import { Head, router, useForm } from '@inertiajs/react';
import { useState } from 'react';
import AdminLayout from '@/Layouts/AdminLayout';
import { collectionRows, courseName, EmptyRow, Field, ObeHeader, Panel, StatusBadge } from '@/Components/ObeUi';

export default function Assessments({ assessments = [], mataKuliahs = [], courses = [], cpmks = [], subCpmks = [], filters = {} }) {
    const rows = collectionRows(assessments); const courseRows = collectionRows(mataKuliahs).length ? collectionRows(mataKuliahs) : collectionRows(courses); const [courseId, setCourseId] = useState(filters.mata_kuliah_id || filters.course_id || '');
    const assessment = useForm({ mata_kuliah_id: courseId, title: '', type: 'tugas', description: '', max_score: 100, weight: '', status: 'aktif' }); const mapping = useForm({ assessment_id: '', cpmk_id: '', sub_cpmk_id: '', weight: '' });
    const create = (event) => { event.preventDefault(); assessment.post('/admin/obe/assessments', { onSuccess: () => assessment.reset('title', 'type', 'description', 'max_score', 'weight') }); };
    const mapOutcome = (event, item) => { event.preventDefault(); mapping.transform((data) => ({ ...data, assessment_id: item.id })).post(`/admin/obe/assessments/${item.id}/mappings`, { onSuccess: () => { mapping.reset(); mapping.transform((data) => data); } }); };
    return <AdminLayout title="Assessment OBE"><Head title="Assessment OBE" /><div className="min-h-dvh space-y-6 bg-neutral-50 p-6"><ObeHeader title="ASSESSMENT OBE" description="Kelola instrumen penilaian dan ukur CPMK atau Sub-CPMK dengan bobot yang jelas." />
        <Panel><form onSubmit={(e) => { e.preventDefault(); router.get('/admin/obe/assessments', { mata_kuliah_id: courseId }, { preserveState: true, replace: true }); }} className="flex flex-wrap gap-3"><select value={courseId} onChange={(e) => { setCourseId(e.target.value); assessment.setData('mata_kuliah_id', e.target.value); }} className="min-w-64 flex-1 border-neutral-300 text-sm"><option value="">Pilih mata kuliah</option>{courseRows.map((course) => <option key={course.id} value={course.id}>{course.kode_mata_kuliah || course.kode || course.code} — {courseName(course)}</option>)}</select><button className="bg-black px-4 py-2 text-xs font-bold text-white">Tampilkan</button></form></Panel>
        {courseId && <Panel><h2 className="mb-4 font-bold">Tambah Assessment</h2><form onSubmit={create} className="grid gap-4 md:grid-cols-2"><Field label="Judul" error={assessment.errors.title}><input required value={assessment.data.title} onChange={(e) => assessment.setData('title', e.target.value)} className="w-full border-neutral-300 text-sm" placeholder="Contoh: Project Akhir" /></Field><Field label="Jenis Assessment" error={assessment.errors.type}><select value={assessment.data.type} onChange={(e) => assessment.setData('type', e.target.value)} className="w-full border-neutral-300 text-sm"><option value="tugas">Tugas</option><option value="quiz">Quiz</option><option value="uts">UTS</option><option value="uas">UAS</option><option value="project">Project</option><option value="praktikum">Praktikum</option></select></Field><Field label="Skor Maksimal" error={assessment.errors.max_score}><input required type="number" min="1" value={assessment.data.max_score} onChange={(e) => assessment.setData('max_score', e.target.value)} className="w-full border-neutral-300 text-sm" /></Field><Field label="Bobot Nilai (%)" error={assessment.errors.weight}><input required type="number" min="0" max="100" step="0.01" value={assessment.data.weight} onChange={(e) => assessment.setData('weight', e.target.value)} className="w-full border-neutral-300 text-sm" /></Field><Field label="Deskripsi" error={assessment.errors.description} className="md:col-span-2"><textarea rows="3" value={assessment.data.description} onChange={(e) => assessment.setData('description', e.target.value)} className="w-full border-neutral-300 text-sm" /></Field><div className="md:col-span-2"><button disabled={assessment.processing} className="bg-black px-4 py-2 text-xs font-bold text-white">{assessment.processing ? 'Menyimpan...' : 'Tambah Assessment'}</button></div></form></Panel>}
        <div className="space-y-4">{rows.map((item) => { const links = collectionRows(item.cpmk_mappings || item.cpmkMappings || item.mappings); return <Panel key={item.id}><div className="flex flex-wrap justify-between gap-3"><div><div className="flex items-center gap-2"><h2 className="font-bold">{item.judul || item.title || item.name}</h2><StatusBadge value={item.status} /></div><p className="mt-1 text-sm text-neutral-500">{item.jenis || item.type} · Maks. {item.skor_maksimal || item.max_score || 100} · Bobot {item.bobot ?? item.weight ?? 0}%</p></div><button onClick={() => { if (confirm(`Hapus assessment ${item.judul || item.title}?`)) router.delete(`/admin/obe/assessments/${item.id}`); }} className="text-xs font-bold text-red-700 underline">Hapus</button></div><div className="mt-4 flex flex-wrap gap-2">{links.map((link) => <span key={link.id} className="border border-indigo-200 bg-indigo-50 px-2 py-1 text-xs text-indigo-800">{link.cpmk?.kode || link.sub_cpmk?.kode || link.cpmk_id || link.sub_cpmk_id} · {link.bobot ?? link.weight}%</span>)}{links.length === 0 && <p className="text-xs text-neutral-500">Belum dipetakan ke capaian.</p>}</div><form onSubmit={(e) => mapOutcome(e, item)} className="mt-4 grid gap-3 border-t border-neutral-200 pt-4 md:grid-cols-3"><select value={mapping.data.cpmk_id} onChange={(e) => mapping.setData('cpmk_id', e.target.value)} className="border-neutral-300 text-sm"><option value="">Pilih CPMK</option>{collectionRows(cpmks).map((cpmk) => <option key={cpmk.id} value={cpmk.id}>{cpmk.kode || cpmk.code} — {cpmk.nama || cpmk.title}</option>)}</select><select value={mapping.data.sub_cpmk_id} onChange={(e) => mapping.setData('sub_cpmk_id', e.target.value)} className="border-neutral-300 text-sm"><option value="">Atau pilih Sub-CPMK</option>{collectionRows(subCpmks).map((sub) => <option key={sub.id} value={sub.id}>{sub.kode || sub.code} — {sub.nama || sub.title}</option>)}</select><div className="flex gap-2"><input required type="number" min="0" max="100" step="0.01" value={mapping.data.weight} onChange={(e) => mapping.setData('weight', e.target.value)} className="w-24 border-neutral-300 text-sm" placeholder="Bobot" /><button className="bg-black px-3 py-2 text-xs font-bold text-white">Petakan</button></div></form></Panel>; })}{rows.length === 0 && <Panel><p className="py-5 text-center text-sm text-neutral-500">Belum ada assessment untuk mata kuliah ini.</p></Panel>}</div></div></AdminLayout>;
}
