import { Head, router, useForm } from '@inertiajs/react';
import { useMemo, useState } from 'react';
import AdminLayout from '@/Layouts/AdminLayout';
import { collectionRows, courseName, curriculumName, DomainBadge, EmptyRow, Field, ObeHeader, Panel } from '@/Components/ObeUi';

const mappingValue = (mappings, cplId, courseId) => { const found = mappings.find((item) => String(item.cpl_id) === String(cplId) && String(item.mata_kuliah_id || item.course_id) === String(courseId)); return found?.bobot ?? found?.weight ?? ''; };

export default function Mapping({ cpls = [], mataKuliahs = [], courses = [], cplCourseMappings = [], courseCplMappings = [], cpmks = [], cpmkCplMappings = [], kurikulums = [], curriculums = [], filters = {} }) {
    const cplRows = collectionRows(cpls); const courseRows = collectionRows(mataKuliahs).length ? collectionRows(mataKuliahs) : collectionRows(courses); const courseMappings = collectionRows(cplCourseMappings).length ? collectionRows(cplCourseMappings) : collectionRows(courseCplMappings); const cpmkRows = collectionRows(cpmks); const curricula = collectionRows(kurikulums).length ? collectionRows(kurikulums) : collectionRows(curriculums);
    const [kurikulumId, setKurikulumId] = useState(filters.kurikulum_id || filters.curriculum_id || ''); const [weights, setWeights] = useState(() => Object.fromEntries(courseMappings.map((item) => [`${item.cpl_id}:${item.mata_kuliah_id || item.course_id}`, item.bobot ?? item.weight ?? ''])));
    const cpmkMap = useForm({ cpmk_id: '', cpl_id: '', weight: '' });
    const visibleCourses = useMemo(() => courseRows.filter((course) => !kurikulumId || String(course.kurikulum_id || course.curriculum_id || course.pivot?.kurikulum_id) === String(kurikulumId)), [courseRows, kurikulumId]);
    const saveWeight = (cpl, course, value) => {
        if (!value || Number(value) <= 0) return;
        router.post('/admin/obe/mapping/cpl-course', { cpl_id: cpl.id, mata_kuliah_id: course.id, kurikulum_id: cpl.kurikulum_id || cpl.curriculum_id || kurikulumId, weight: Number(value) }, { preserveScroll: true });
    };
    const addCpmkMapping = (event) => { event.preventDefault(); cpmkMap.post('/admin/obe/mapping/cpmk-cpl', { onSuccess: () => cpmkMap.reset() }); };
    const removeCpmkMapping = (mapping) => { if (confirm('Hapus mapping CPMK ke CPL ini?')) router.delete(`/admin/obe/mapping/cpmk-cpl/${mapping.id}`); };
    return <AdminLayout title="Pemetaan OBE"><Head title="Pemetaan OBE" /><div className="min-h-dvh space-y-6 bg-neutral-50 p-6"><ObeHeader title="PEMETAAN OBE" description="Atur kontribusi mata kuliah terhadap CPL dan keterkaitan CPMK terhadap CPL." />
        <Panel><div className="flex flex-wrap items-end gap-3"><Field label="Kurikulum" className="min-w-64 flex-1"><select value={kurikulumId} onChange={(e) => setKurikulumId(e.target.value)} className="w-full border-neutral-300 text-sm"><option value="">Semua kurikulum</option>{curricula.map((item) => <option key={item.id} value={item.id}>{curriculumName(item)}</option>)}</select></Field><button onClick={() => router.get('/admin/obe/mapping', { kurikulum_id: kurikulumId }, { preserveState: true, replace: true })} className="bg-black px-4 py-2 text-xs font-bold text-white">Terapkan Filter</button></div></Panel>
        <Panel className="overflow-x-auto !p-0"><div className="border-b border-neutral-200 px-5 py-4"><h2 className="font-bold">Matriks CPL — Mata Kuliah</h2><p className="mt-1 text-xs text-neutral-500">Isi bobot kontribusi (0–100), lalu pindahkan fokus dari kolom untuk menyimpan relasi.</p></div><table className="min-w-full text-sm"><thead className="bg-neutral-50 text-left text-xs uppercase text-neutral-500"><tr><th className="sticky left-0 z-10 bg-neutral-50 px-4 py-3">CPL</th>{visibleCourses.map((course) => <th key={course.id} className="min-w-36 px-3 py-3"><span className="block font-bold">{course.kode_mata_kuliah || course.kode || course.code}</span><span className="normal-case font-normal">{courseName(course)}</span></th>)}</tr></thead><tbody className="divide-y divide-neutral-100">{cplRows.map((cpl) => <tr key={cpl.id}><td className="sticky left-0 z-10 bg-white px-4 py-3"><p className="font-bold">{cpl.kode || cpl.code}</p><DomainBadge value={cpl.domain || cpl.category} /></td>{visibleCourses.map((course) => { const key = `${cpl.id}:${course.id}`; const value = weights[key] ?? mappingValue(courseMappings, cpl.id, course.id); return <td key={course.id} className="px-3 py-3"><input type="number" min="0" max="100" step="0.01" aria-label={`Bobot ${cpl.kode || cpl.code} untuk ${courseName(course)}`} value={value} onChange={(e) => setWeights((prev) => ({ ...prev, [key]: e.target.value }))} onBlur={() => saveWeight(cpl, course, value)} className="w-20 border-neutral-300 text-center text-sm" placeholder="—" /></td>; })}</tr>)}{cplRows.length === 0 && <EmptyRow colSpan={Math.max(visibleCourses.length + 1, 2)}>Belum ada CPL untuk ditampilkan.</EmptyRow>}</tbody></table></Panel>
        <Panel><h2 className="font-bold">Mapping CPMK — CPL</h2><p className="mt-1 text-sm text-neutral-500">Hubungkan CPMK dengan CPL yang sesuai dan tetapkan bobot kontribusinya.</p><form onSubmit={addCpmkMapping} className="mt-5 grid gap-3 md:grid-cols-2 lg:grid-cols-4"><Field label="CPMK" error={cpmkMap.errors.cpmk_id}><select required value={cpmkMap.data.cpmk_id} onChange={(e) => cpmkMap.setData('cpmk_id', e.target.value)} className="w-full border-neutral-300 text-sm"><option value="">Pilih CPMK</option>{cpmkRows.map((item) => <option key={item.id} value={item.id}>{item.kode || item.code} — {item.nama || item.title || item.name}</option>)}</select></Field><Field label="CPL" error={cpmkMap.errors.cpl_id}><select required value={cpmkMap.data.cpl_id} onChange={(e) => cpmkMap.setData('cpl_id', e.target.value)} className="w-full border-neutral-300 text-sm"><option value="">Pilih CPL</option>{cplRows.map((item) => <option key={item.id} value={item.id}>{item.kode || item.code} — {item.nama || item.title || item.name}</option>)}</select></Field><Field label="Bobot (%)" error={cpmkMap.errors.weight}><input required type="number" min="0" max="100" step="0.01" value={cpmkMap.data.weight} onChange={(e) => cpmkMap.setData('weight', e.target.value)} className="w-full border-neutral-300 text-sm" /></Field><div className="flex items-end"><button disabled={cpmkMap.processing} className="w-full bg-black px-4 py-2 text-xs font-bold text-white">Tambah Mapping</button></div></form><div className="mt-5 overflow-x-auto border border-neutral-200"><table className="min-w-full text-sm"><thead className="bg-neutral-50 text-left text-xs uppercase text-neutral-500"><tr><th className="px-4 py-3">CPMK</th><th className="px-4 py-3">CPL</th><th className="px-4 py-3">Bobot</th><th className="px-4 py-3">Aksi</th></tr></thead><tbody className="divide-y divide-neutral-100">{collectionRows(cpmkCplMappings).map((item) => <tr key={item.id}><td className="px-4 py-3">{item.cpmk?.kode || item.cpmk?.code || item.cpmk_id}</td><td className="px-4 py-3">{item.cpl?.kode || item.cpl?.code || item.cpl_id}</td><td className="px-4 py-3">{item.bobot ?? item.weight}%</td><td className="px-4 py-3"><button onClick={() => removeCpmkMapping(item)} className="text-xs font-bold text-red-700 underline">Hapus</button></td></tr>)}{collectionRows(cpmkCplMappings).length === 0 && <EmptyRow colSpan={4}>Belum ada mapping CPMK ke CPL.</EmptyRow>}</tbody></table></div></Panel></div></AdminLayout>;
}
