import { Head, router } from '@inertiajs/react';
import { useMemo, useState } from 'react';
import AdminLayout from '@/Layouts/AdminLayout';
import { collectionRows, curriculumName, DomainBadge, EmptyRow, ObeHeader, Panel } from '@/Components/ObeUi';

const percentage = (value) => value === null || value === undefined || value === '' ? '-' : `${Number(value).toFixed(1)}%`;
const tone = (value, target = 70) => Number(value || 0) >= Number(target) ? 'bg-emerald-100 text-emerald-800' : 'bg-rose-100 text-rose-800';

export default function Report({ kurikulums = [], curriculums = [], filters = {}, cpls = [], mataKuliahs = [], courses = [], matrix = [], cplCourseMatrix = [], achievements = [], cplAchievements = [], gaps = [], target = 70 }) {
    const curricula = collectionRows(kurikulums).length ? collectionRows(kurikulums) : collectionRows(curriculums); const cplRows = collectionRows(cpls); const courseRows = collectionRows(mataKuliahs).length ? collectionRows(mataKuliahs) : collectionRows(courses); const grid = collectionRows(matrix).length ? collectionRows(matrix) : collectionRows(cplCourseMatrix); const achievementRows = collectionRows(achievements).length ? collectionRows(achievements) : collectionRows(cplAchievements); const gapRows = collectionRows(gaps);
    const [kurikulumId, setKurikulumId] = useState(filters.kurikulum_id || filters.curriculum_id || '');
    const coverageFor = useMemo(() => new Map(grid.map((item) => [`${item.cpl_id}:${item.mata_kuliah_id || item.course_id}`, item.bobot ?? item.weight ?? item.value ?? 0])), [grid]);
    return <AdminLayout title="Laporan OBE"><Head title="Laporan OBE" /><div className="min-h-dvh space-y-6 bg-neutral-50 p-6"><ObeHeader title="LAPORAN KETER CAPAIAN OBE" description="Tinjau pemetaan CPL, capaian, dan gap yang membutuhkan tindak lanjut." />
        <Panel><div className="flex flex-wrap items-end gap-3"><div className="min-w-64 flex-1"><label className="mb-1 block text-xs font-bold uppercase">Kurikulum</label><select value={kurikulumId} onChange={(e) => setKurikulumId(e.target.value)} className="w-full border-neutral-300 text-sm"><option value="">Pilih kurikulum</option>{curricula.map((item) => <option key={item.id} value={item.id}>{curriculumName(item)}</option>)}</select></div><button onClick={() => router.get('/admin/obe/report', { kurikulum_id: kurikulumId }, { preserveState: true, replace: true })} className="bg-black px-4 py-2 text-xs font-bold text-white">Tampilkan Laporan</button></div></Panel>
        <Panel className="overflow-x-auto !p-0"><div className="border-b border-neutral-200 px-5 py-4"><h2 className="font-bold">Matriks CPL — Mata Kuliah</h2><p className="mt-1 text-xs text-neutral-500">Bobot menunjukkan kontribusi mata kuliah pada CPL.</p></div><table className="min-w-full text-sm"><thead className="bg-neutral-50 text-left text-xs uppercase text-neutral-500"><tr><th className="sticky left-0 z-10 bg-neutral-50 px-4 py-3">CPL</th>{courseRows.map((course) => <th key={course.id} className="min-w-28 px-3 py-3">{course.kode_mata_kuliah || course.kode || course.code}</th>)}</tr></thead><tbody className="divide-y divide-neutral-100">{cplRows.map((cpl) => <tr key={cpl.id}><td className="sticky left-0 z-10 bg-white px-4 py-3"><p className="font-bold">{cpl.kode || cpl.code}</p><DomainBadge value={cpl.domain || cpl.category} /></td>{courseRows.map((course) => { const value = coverageFor.get(`${cpl.id}:${course.id}`); return <td key={course.id} className="px-3 py-3 text-center">{value ? <span className="inline-flex bg-indigo-100 px-2 py-1 text-xs font-bold text-indigo-800">{value}%</span> : <span className="text-neutral-300">—</span>}</td>; })}</tr>)}{cplRows.length === 0 && <EmptyRow colSpan={Math.max(courseRows.length + 1, 2)}>Data matriks belum tersedia.</EmptyRow>}</tbody></table></Panel>
        <div className="grid gap-6 xl:grid-cols-[1.5fr_1fr]"><Panel className="overflow-x-auto !p-0"><div className="border-b border-neutral-200 px-5 py-4"><h2 className="font-bold">Capaian CPL</h2><p className="mt-1 text-xs text-neutral-500">Target ketercapaian: {target}%</p></div><table className="min-w-full text-sm"><thead className="bg-neutral-50 text-left text-xs uppercase text-neutral-500"><tr><th className="px-4 py-3">CPL</th><th className="px-4 py-3">Evidence</th><th className="px-4 py-3">Capaian</th><th className="px-4 py-3">Status</th></tr></thead><tbody className="divide-y divide-neutral-100">{achievementRows.map((item) => { const value = item.capaian ?? item.achievement ?? item.percentage ?? item.nilai; return <tr key={item.id || item.cpl_id}><td className="px-4 py-3"><p className="font-bold">{item.cpl?.kode || item.kode || item.code}</p><p className="text-xs text-neutral-500">{item.cpl?.nama || item.nama || item.title || ''}</p></td><td className="px-4 py-3">{item.evidence_count ?? item.assessment_count ?? '—'}</td><td className="px-4 py-3 font-bold">{percentage(value)}</td><td className="px-4 py-3"><span className={`inline-flex px-2 py-1 text-[10px] font-bold uppercase ${tone(value, item.target ?? target)}`}>{Number(value || 0) >= Number(item.target ?? target) ? 'Tercapai' : 'Perlu tindak lanjut'}</span></td></tr>; })}{achievementRows.length === 0 && <EmptyRow colSpan={4}>Belum ada evidence capaian untuk dilaporkan.</EmptyRow>}</tbody></table></Panel>
            <Panel><h2 className="font-bold">Analisis Gap</h2><p className="mt-1 text-sm text-neutral-500">CPL di bawah target perlu dievaluasi pada mata kuliah dan assessment terkait.</p><div className="mt-4 space-y-3">{gapRows.map((gap) => <article key={gap.id || gap.cpl_id} className="border border-rose-200 bg-rose-50 p-4"><div className="flex items-center justify-between gap-3"><p className="font-bold text-rose-950">{gap.cpl?.kode || gap.kode || gap.code}</p><span className="text-sm font-bold text-rose-800">{percentage(gap.capaian ?? gap.achievement ?? gap.percentage)}</span></div><p className="mt-1 text-sm text-rose-900">{gap.cpl?.nama || gap.nama || gap.title || gap.rekomendasi || gap.recommendation || 'Ketercapaian belum memenuhi target.'}</p>{(gap.rekomendasi || gap.recommendation) && <p className="mt-2 text-xs text-rose-800"><b>Tindak lanjut:</b> {gap.rekomendasi || gap.recommendation}</p>}</article>)}{gapRows.length === 0 && <p className="border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-800">Tidak ada gap capaian pada data yang tersedia.</p>}</div></Panel></div></div></AdminLayout>;
}
